# Federated_Learning_Forge
If you run the code and you get some error that's about not being able to get the dataset or whatever, download the data for MNIST from this link https://github.com/golbin/TensorFlow-MNIST
The pi already has it, but if you need it on your machine, use that link. I was not able to upload all of its files since GitHub said the file was too large :( Theoretically, there shouldn't be an issue because the pi already has all the file it needs for the MNIST dataset, but if you do run into an error like this (which I pray you don't), use that link and once the zip file is downloaded, move it to the same directory as the utils.py, client.py, and server.py.

Once the zip file is moved to the directory, unzip it. You will see a folder of the same name as the zip file, change that file name to "data". If this doesn't solve the issue, let me know and I'll see what I can do.
